language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=src/main.cpp
install:
    - pip install -U platformio
script:
    - pio remote -a rpi1 run -t upload -e nodemcuv2
    - pio remote -a rpi1 test -e nodemcuv2

